apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: sirius-ops-develop
spec:
  serviceAccountName: kubewatch
  containers:
  - image: bitnami/kubewatch #using this image, its more stable and active
    securityContext:
      runAsUser: 0
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch