apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
  namespace: sirius-ops-develop
data:
  .kubewatch.yaml: |
    namespace: "sirius-ops-develop"
    handler:
      webhook:
        url: "https://hooks.slack.com/services/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"
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
      secret: false
      configmap: false
